### ISSUE TITLE
Hai sir  i am unable to get   NEXTAUTH_URL=

### ISSUE THREAD

**Issue by ghost** [MartsTech/chatgpt-clone#24]
Hi sir from where will i get these keys 

NEXTAUTH_URL=
NEXTAUTH_SECRE=
NEXT_PUBLIC_API_URL=

**Comment by MartsTech** [comment]
Hi, usually there should be comments explaining this, but I have missed that for this project. 

`NEXTAUTH_URL` should be `http://localhost:3000`, 
`NEXTAUTH_SECRET` is whethever, for example `my-secret-key`,
`NEXT_PUBLIC_API_URL` should be `http://localhost:3000/api`.

 I am going based on memory right now, but this should be right.
